// ------------------------------------------------------------------------------
//  Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

// **NOTE** This file was generated by a tool and any changes will be overwritten.


namespace Microsoft.Graph.Test.Mocks
{
    using System;
    using System.Collections.Generic;

    using Newtonsoft.Json;

    /// <summary>
    /// Test class for testing serialization of an IEnumerable of DateTimeOffset.
    /// </summary>
    public class EdmDateEnumerableClass
    {
        /// <summary>
        /// Gets or sets StartDate.
        /// </summary>
        public IEnumerable<EdmDate> StartDate { get; set; }
    }
}
