# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Validate pull requests to master and dev branches.

pr:
  branches:
    include:
    - master
    - dev
    - feature/2.0
  paths:
    exclude:
        - .github/*
        - build/*
        - docs/*
        - pipelines/*
        - scripts/*
        - .gitignore
        - CONTRIBUTING.md
        - LICENSE.txt
        - Microsoft.Graph.Core.sln
        - README.md
        - THIRD PARTY NOTICES
        - appveyor.yml

trigger: none # disable triggers based on commits.

variables:
  PACKAGE_NAME: 'microsoft.graph.core'
  PROJECT_PATH: '.\src\Microsoft.Graph.Core\Microsoft.Graph.Core.csproj'

pool:
  name: Microsoft Graph
  demands:
  - msbuild
  - vstest

steps:
- checkout: self
  clean: true
  fetchDepth: 1

- task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@2
  displayName: 'Run CredScan'
  inputs:
    debugMode: false

- task: PowerShell@2
  displayName: 'Validate updated version'
  inputs:
    targetType: filePath
    filePath: 'scripts\ValidateUpdatedNugetVersion.ps1'
    arguments: '-packageName "$(PACKAGE_NAME)" -projectPath "$(PROJECT_PATH)"'
  enabled: true

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    vstsFeed: '/f887743a-88c6-4716-b4aa-50761b543a15'

- task: MSBuild@1
  displayName: 'Build solution to run unit test'
  inputs:
    configuration: debug
    clean: true

- task: VSTest@2
  displayName: 'Run enabled tests'
  # inputs:
  #   testAssemblyVer2: '**\Microsoft.Graph.DotnetCore.Core.Test.dll'
  #   searchFolder: '$(System.DefaultWorkingDirectory)'

- task: YodLabs.O365PostMessage.O365PostMessageBuild.O365PostMessageBuild@0
  displayName: 'Graph Client Tooling pipeline fail notification'
  inputs:
    addressType: serviceEndpoint
    serviceEndpointName: 'microsoftgraph pipeline status'
    title: '$(Build.DefinitionName) failure notification'
    text: 'This pipeline has failed. View the build details for further information. This is a blocking failure. '
  condition: failed()
  enabled: true
