trigger: none
pr: none

schedules:
  - cron: '0 0 * * *'
    displayName: Daily builds
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      image: windows-latest
      os: windows
    sdl:
      sourceAnalysisPool:
        name: Azure-Pipelines-1ESPT-ExDShared
        image: windows-2022
        os: windows
      credscan:
        enabled: true
      policheck:
        enabled: true
      binskim:
        enabled: true
    stages:
      - stage: Build
        jobs:
          - job: Build
            displayName: Build .NET Core SDK
            steps:
              - checkout: self
                submodules: recursive

              - task: UseDotNet@2
                displayName: Set up .NET 8
                inputs:
                  packageType: 'sdk'
                  version: 8.x

              - task: UseDotNet@2
                displayName: Set up .NET 10
                inputs:
                  packageType: 'sdk'
                  version: 10.x

              - task: NuGetAuthenticate@1
                displayName: Authenticate to Azure Artifacts

              - powershell: |
                  @"
                  <?xml version="1.0" encoding="utf-8"?>
                  <configuration>
                    <packageSources>
                      <clear />
                      <add key="GraphDeveloperExperiences_Public" value="https://microsoftgraph.pkgs.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_packaging/GraphDeveloperExperiences_Public/nuget/v3/index.json" />
                    </packageSources>
                  </configuration>
                  "@ | Set-Content -Path "$(Build.SourcesDirectory)\nuget.config" -Encoding UTF8
                displayName: Create nuget.config

              - script: dotnet restore Microsoft.Graph.Core.sln --configfile nuget.config
                displayName: Restore dependencies
                workingDirectory: $(Build.SourcesDirectory)

              - script: dotnet build Microsoft.Graph.Core.sln --no-restore
                displayName: Build SDK
                workingDirectory: $(Build.SourcesDirectory)

              - script: dotnet test Microsoft.Graph.Core.sln --no-build
                displayName: Run unit tests
                workingDirectory: $(Build.SourcesDirectory)
